# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

sum = 0

latest_pair = [1, 2]

def update_fib_pair():
    previous_latest_num = latest_pair.copy()
    latest_pair[0] = previous_latest_num[1]
    latest_pair[1] = previous_latest_num[0] + previous_latest_num[1]

def check_even(x):
    if x % 2 == 0:
        return True

while latest_pair[1]<4000000:
    if check_even(latest_pair[1]):
        sum += latest_pair[1]
    update_fib_pair()
    print(latest_pair)

print(sum)